[build-system]
requires = ["setuptools>=61"]
build-backend = "setuptools.build_meta"

[project]
name = "key-service"
version = "0.1.0"

[tool.setuptools]
package-dir = {"" = "src"}
py-modules = ["app"]
