name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ "**" ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  sqlite:
    name: Unit tests (SQLite, SQLAlchemy)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run pytest (SQLite)
        env:
          STORAGE_BACKEND: sqlalchemy
          # in-memory SQLite; no DSN needed
        run: |
          pytest -q

  postgres:
    name: Integration tests (Postgres via docker-compose)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Optional but useful for cross-platform builds
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Compose up (tests)
        run: |
          docker compose -f docker-compose.test.yml up --build --abort-on-container-exit --exit-code-from tests
        # Always dump logs if something fails so PRs are debuggable
      - name: Dump compose logs on failure
        if: failure()
        run: |
          docker compose -f docker-compose.test.yml logs --no-color || true

      - name: Compose down
        if: always()
        run: |
          docker compose -f docker-compose.test.yml down -v
